{% set name = "cuda-nvcc-split" %}
{% set version = "12.1.105" %}
{% set cuda_version = "12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Using this license for consistent messaging with the components it relies on
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvcc/LICENSE.txt
  sha256: 5db25d4fd138013b563f9a3d1d87f7de7df1dac014fd4cccdfbb3435a5cff761

build:
  number: 0
  skip: true  # [osx]
  skip: true  # [target_platform != "linux-64" and target_platform != cross_target_platform]

outputs:
  - name: cuda-nvcc
    build:
      skip: True  # [target_platform != cross_target_platform]
    requirements:
      run:
        - cuda-nvcc_{{ target_platform }} {{ version }}.*

        # cuda-nvcc has runtime dependencies on C and C++ compilers, but needs
        # to support a wider range of host compilers than only the latest
        # versions pinned in conda-forge-pinning-feedstock. Therefore, we
        # cannot just list compiler('c') and compiler('cxx') as dependencies.
        # However, we only need to do this for Linux because Windows has
        # separate package names for each compiler version, like vs2019 and
        # vs2022, and we can use compiler('c') and compiler('cxx') to get
        # those.
        #
        # The compiler names for compiler('c') and compiler('cxx') come from
        # https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml
        # The supported host compiler versions for a given nvcc version come from
        # https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
        # https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html
        - gcc_{{ target_platform }} >=6,<13  # [linux]
        - gxx_{{ target_platform }} >=6,<13  # [linux]
        - compiler('c')    # [not linux]
        - compiler('cxx')  # [not linux]
    test:
      commands:
        - test -f $PREFIX/bin/nvcc                          # [linux]
        - if not exist %LIBRARY_BIN%\nvcc.exe exit 1        # [win]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE.txt
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Compiler for CUDA applications.
      description: |
        Compiler for CUDA applications.
      doc_url: https://docs.nvidia.com/cuda/index.html

  - name: cuda-nvcc_{{ cross_target_platform }}
    run_exports:
      strong:
        - cuda-version >={{ cuda_version }},<{{ cuda_version.split(".")[0]|int + 1 }}
    files:
      - etc/conda/activate.d/~cuda-nvcc_activate.sh       # [linux]
      - etc/conda/deactivate.d/~cuda-nvcc_deactivate.sh   # [linux]
      - etc/conda/activate.d/~cuda-nvcc_activate.bat      # [win]
      - etc/conda/deactivate.d/~cuda-nvcc_deactivate.bat  # [win]
    requirements:
      host:
        - sysroot_{{ cross_target_platform }} 2.17.*  # [linux]
      run:
        - cuda-nvcc-dev_{{ cross_target_platform }} {{ version }}.*
        - cuda-cudart-dev_{{ cross_target_platform }} {{ cuda_version }}.*
        - cuda-driver-dev_{{ cross_target_platform }} {{ cuda_version }}.*  # [linux]
        - cuda-nvcc-tools {{ version }}.*
        - cuda-nvcc-impl {{ version }}.*   # [target_platform == cross_target_platform]
        - {{ pin_compatible("sysroot_" ~ cross_target_platform, max_pin="x.x") }}  # [linux]
    test:
      requires:
        - {{ c_compiler }}_{{ cross_target_platform }} {{ c_compiler_version }}.*      # [linux]
        - {{ cxx_compiler }}_{{ cross_target_platform }} {{ cxx_compiler_version }}.*  # [linux]
        - {{ c_compiler }}_{{ cross_target_platform }}    # [win]
        - {{ cxx_compiler }}_{{ cross_target_platform }}  # [win]
        - cmake
        - ninja
        - git    # [linux]
      files:
        - test.cpp
        - test.cu
        - CMakeLists.txt
        - run_cmake_cuda_tests.sh  # [linux]
      commands:
        - nvcc --version
        - $CXX --verbose ${CXXFLAGS} -lcuda -lcudart_static test.cpp  # [linux]
        - cl /Tp test.cpp /link /LIBPATH:"%CONDA_PREFIX%\Library\lib" cudart_static.lib /out:test_nvcc.exe  # [win]
        - nvcc --verbose test.cu
        - cmake ${CMAKE_ARGS} -S . -B ./build -G=Ninja
        - cmake --build ./build -v
        - bash ./run_cmake_cuda_tests.sh  # [linux]
        - test -f $PREFIX/etc/conda/activate.d/~cuda-nvcc_activate.sh      # [linux]
        - test -f $PREFIX/etc/conda/deactivate.d/~cuda-nvcc_deactivate.sh  # [linux]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE.txt
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Compiler activation scripts for CUDA applications.
      description: |
        Compiler for CUDA applications.
      doc_url: https://docs.nvidia.com/cuda/index.html

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Compiler for CUDA applications.
  description: |
    Compiler for CUDA applications.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  feedstock-name: cuda-nvcc
  recipe-maintainers:
    - conda-forge/cuda
