{% set name = "cuda-nvcc-split" %}
{% set version = "12.0.76" %}
{% set cuda_version = "12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Using this license for consistent messaging with the components it relies on
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvcc/LICENSE.txt
  sha256: 5db25d4fd138013b563f9a3d1d87f7de7df1dac014fd4cccdfbb3435a5cff761

build:
  number: 3
  skip: true  # [osx or win]
  skip: true  # [build_platform != "linux-64" and build_platform != target_platform]

outputs:
  - name: cuda-nvcc
    build:
      skip: True  # [target_platform != cross_target_platform]
    requirements:
      run:
        - cuda-nvcc_{{ target_platform }} {{ version }}.*
    test:
      requires:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      commands:
        - test -f $PREFIX/bin/nvcc                          # [linux]
        - if not exist %LIBRARY_BIN%\nvcc.exe exit 1        # [win]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE.txt
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Compiler for CUDA applications.
      description: |
        Compiler for CUDA applications.
      doc_url: https://docs.nvidia.com/cuda/index.html

  - name: cuda-nvcc_{{ cross_target_platform }}
    run_exports:
      strong:
        - cuda-version >={{ cuda_version }},<{{ cuda_version.split(".")[0]|int + 1 }}
    files:
      - etc/conda/activate.d/~cuda-nvcc_activate.sh      # [linux]
      - etc/conda/deactivate.d/~cuda-nvcc_deactivate.sh  # [linux]
    requirements:
      run:
        - cuda-nvcc-dev_{{ cross_target_platform }} {{ version }}.*
        - cuda-cudart-dev_{{ cross_target_platform }} {{ cuda_version }}.*
        - cuda-driver-dev_{{ cross_target_platform }} {{ cuda_version }}.*
        - cuda-nvcc-tools {{ version }}.*
        - cuda-nvcc-impl {{ version }}.*   # [target_platform == cross_target_platform]
        - sysroot_{{ cross_target_platform }}  # [linux]
    test:
      requires:
        - {{ c_compiler }}_{{ cross_target_platform }} {{ c_compiler_version }}.*
        - {{ cxx_compiler }}_{{ cross_target_platform }} {{ cxx_compiler_version }}.*
        - cmake
        - ninja
        - git    # [linux]
      files:
        - test.cu
        - CMakeLists.txt
        - run_cmake_cuda_tests.sh  # [linux]
      commands:
        - nvcc --version
        - nvcc --verbose test.cu
        - cmake ${CMAKE_ARGS} -S . -B ./build -G=Ninja
        - cmake --build ./build -v
        - bash ./run_cmake_cuda_tests.sh  # [linux]
        - test -f $PREFIX/etc/conda/activate.d/~cuda-nvcc_activate.sh      # [linux]
        - test -f $PREFIX/etc/conda/deactivate.d/~cuda-nvcc_deactivate.sh  # [linux]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE.txt
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Compiler for CUDA applications.
      description: |
        Compiler for CUDA applications.
      doc_url: https://docs.nvidia.com/cuda/index.html

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Compiler for CUDA applications.
  description: |
    Compiler for CUDA applications.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  feedstock-name: cuda-nvcc
  recipe-maintainers:
    - adibbley
